{{- if .Values.statefulsets}}
{{- range $i, $sts := .Values.statefulsets}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Values.global.appName }}{{- if $sts.nameSuffix }}-{{ $sts.nameSuffix }}{{- end }}-statefulset
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $.Values.global.appName }}
    app.kubernetes.io/instance: {{ $.Values.global.appName }}-{{ $.Values.global.environment }}
    app.kubernetes.io/component: program
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/statefulset: "{{ $.Values.global.appName }}{{- if $sts.nameSuffix }}-{{ $sts.nameSuffix }}{{- end }}"
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  serviceName: {{ $.Values.global.appName }}{{- if $sts.nameSuffix }}-{{ $sts.nameSuffix }}{{- end }}-headless-service
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $.Values.global.appName }}
      app.kubernetes.io/instance: {{ $.Values.global.appName }}-{{ $.Values.global.environment }}
      app.kubernetes.io/component: program
      app.kubernetes.io/managed-by: argocd
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $.Values.global.appName }}
        app.kubernetes.io/instance: {{ $.Values.global.appName }}-{{ $.Values.global.environment }}
        app.kubernetes.io/component: program
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/statefulset: "{{ $.Values.global.appName }}{{- if $sts.nameSuffix }}-{{ $sts.nameSuffix }}{{- end }}"
    spec:
      {{- if $sts.containers }}
      containers:
      {{- range $j, $container := $sts.containers }}
        - name: {{ $.Values.global.appName }}{{- if $sts.nameSuffix }}-{{ $sts.nameSuffix }}{{- end }}{{- if $container.nameSuffix }}-{{ $container.nameSuffix }}{{- end }}
          image: {{ $container.image }}
          imagePullPolicy: IfNotPresent

          {{- if $container.securityContext }}
          securityContext:
{{ toYaml $container.securityContext | nindent 12 }}
          {{- end }}

          {{- if $container.env}}
          env:
{{ toYaml $container.env | nindent 12 }}
          {{- end }}

          {{- if $container.ports }}
          ports:
{{ toYaml $container.ports | nindent 12 }}
          {{- end }}
            
          {{- if $container.startupProbeHttpGet }}
          startupProbe:
            {{- if $container.startupProbeHttpGet }}
            httpGet:
{{ toYaml $container.startupProbeHttpGet | nindent 14 }}
            {{- end }}
            failureThreshold: 10
            periodSeconds: 5
          {{- end }}

          {{- if $container.readinessProbeHttpGet }}
          readinessProbe:
            {{- if $container.readinessProbeHttpGet }}
            httpGet:
{{ toYaml $container.readinessProbeHttpGet | nindent 14 }}
            {{- end }}
            initialDelaySeconds: 5
            periodSeconds: 2
          {{- end }}

          {{- if $container.livenessProbeHttpGet }}
          livenessProbe:
            {{- if $container.livenessProbeHttpGet }}
            httpGet:
{{ toYaml $container.livenessProbeHttpGet | nindent 14 }}
            {{- end }}
            initialDelaySeconds: 20
            periodSeconds: 10
          {{- end }}

          {{- if $container.resources }}
          resources:
{{ toYaml $container.resources | nindent 12 }}
          {{- end }}

          {{- if $container.volumeMounts }}
          volumeMounts:
{{ toYaml $container.volumeMounts | nindent 12 }}
          {{- end }}

      {{- end }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ $.Values.global.appName }}
                  app.kubernetes.io/instance: {{ $.Values.global.appName }}-{{ $.Values.global.environment }}
                  app.kubernetes.io/component: program
                  app.kubernetes.io/managed-by: argocd
              topologyKey: kubernetes.io/hostname

    
      priorityClassName: {{ $.Values.priorityClassName | default "low-priority" }}

      {{- if $sts.statefulsetSecurityContext }}
      securityContext:
{{ toYaml $sts.statefulsetSecurityContext | nindent 8 }}
      {{- end }}

      {{- if $sts.volumes }}
      volumes:
{{ toYaml $sts.volumes | nindent 8 }}
      {{- end }}

  {{- if $sts.volumeClaimTemplates }}    
  volumeClaimTemplates:
{{ toYaml $sts.volumeClaimTemplates | nindent 4 }}
  {{- end }}
{{- end}}
{{- end}}
